[package]
name = "completion-generator"
version = "0.1.0"
authors = ["Yuma Hiramatsu <yuma.hiramatsu@gmail.com>"]
edition = "2018"

repository = "https://github.com/eduidl/completion-generator"
license = "Apache-2.0"

[dependencies]
itertools = "0.10"
nom = "6.1"
regex = "1.4"
